version: '3.8'

services:
  app:
    build: .
    container_name: zitoluks-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable
    volumes:
      - ./zitoLuks.db:/app/zitoLuks.db
