services:
  app:
    build: .
    container_name: zitoluks-app
    user: "root"
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_CACHE_DIR=/home/pptruser/.cache/puppeteer
    volumes:
      - ./zitoLuks.db:/app/zitoLuks.db
